[workspace]
channels = ["conda-forge"]
name = "tools"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
betfairlightweight = ">=2.22.0, <3"
polars = ">=1.35.2, <2"
b2sdk = ">=2.10.1, <3"
zstandard = ">=0.25.0, <0.26"
