[workspace]
channels = ["conda-forge"]
name = "tools"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
betfairlightweight = ">=2.22.0, <3"
